### ISSUE TITLE
Roadmap for v4

### ISSUE THREAD

**Issue by micimize** [zino-app/graphql-flutter#608]
There are a handful of open PRs and issues that I think should be parceled together for the next major version:
- [X] #564 & #565 (outsource links to gql)
- [x]  many caching fixes:
  - [x] #471 (outsource normalization)
  - [x] #423 (the cache is kinda broken)
- [x] many of the items enumerated by @klavs in https://github.com/zino-app/graphql-flutter/issues/563#issuecomment-587806331

The **main question** is should we make a `v4` branch or something to avoid every merge auto-publishing a breaking change? **Or**, should we rework CI such that `master` is the main development branch, and have `master, beta, stable`? **Or** should we just temporarily disable CI and then re-enable after achieving a stable API?

@HofmannZ @eusdima @mainawycliffe

**Comment by mainawycliffe** [comment]
Since we will most likely be introducing breaking changes, version 4 makes sense. Yeah, we can disable the ci temporarily and enable it ones we have an idea of what exactly we are testing and how to deal with it.

**Comment by teknolojia** [comment]
can we get cookie storage in v4?

**Comment by micimize** [comment]
@teknolojia we can make cookie support a higher priority, yes

**Comment by micimize** [comment]
I've decided to move working on `graphql_flutter` to the top of my [priority queue][queue], particularly working on [`v4`][v4].

To support development please [sponsor me][me] or the [graphql-flutter open collective][oc] if you can.

[queue]: https://github.com/zino-app/graphql-flutter/issues/420#issuecomment-606340132
[v4]: https://github.com/zino-app/graphql-flutter/projects/3
[me]: https://github.com/sponsors/micimize
[oc]: https://opencollective.com/graphql-flutter

**Comment by klavs** [comment]
FYI, @iscriptology just ported websocket link from `graphql_flutter` to `gql_link`.
I'm currently working on an `ErrorLink` with an example `HttpAuthLink` implementation.

For full feature parity, `gql_link` is missing file upload. (Because that's not a standardized feature of GraphQL). 

Other than that, I feel that `gql_link` is soon to be ready for v4-alpha to be tested in the wild.

**Comment by micimize** [comment]
Merged #564 & #565 and will be treating `modularization` as the v4 branch.

Some related todos for myself
- [ ] Update docs and examples
- [ ] Grok gql's error system and it's [integration with ours](https://github.com/zino-app/graphql-flutter/pull/564/files#diff-2dc31043f826a5c66a6ae8e16fd48560)
- [ ] [`// TODO: handle Link exceptions`](https://github.com/zino-app/graphql-flutter/pull/564/files#diff-84432fc4e06f21afd2a827eb90fb5e74R142)
- [ ] file upload link

**Comment by micimize** [comment]
Considering adding default `json.encode` logic / options to the roadmap (#642)

**Comment by micimize** [comment]
@teknolojia `v4` uses `gql_link`, for which there is [`gql_dio_link`](https://github.com/TarekkMA/gql_dio_link). `dio` has a [cookie manager plugin](https://pub.dev/packages/dio_cookie_manager) for `dart:io` contexts and regular cookie support [in the browser](https://github.com/flutterchina/dio/issues/585#issuecomment-568668589). Would that be enough for your session management?

`http` also has the [`withCredentials](https://pub.dev/documentation/http/latest/browser_client/BrowserClient/withCredentials.html) config in the browser, but seems fairly [lacking in cookie support](https://github.com/dart-lang/http/issues?q=cookies)

**Comment by micimize** [comment]
I've been making slow and steady progress here – got the starwars example running again today, and have been adding better docstrings. Will probably start diffing against beta to avoid clobbering recent changes and then publish an `alpha` version for people to start using tomorrow.

some things I might consider working on after a stable release candidate is ready:
* significantly overhauling the flutter api (possibly with [`flutter_hooks`](https://github.com/rrousselGit/flutter_hooks))
* I'm following [this discussion on embedded api docs](https://github.com/rrousselGit/flutter_hooks/issues/118) – would be pretty cool if we could get working in-browser examples, but

**Comment by JigneshPatel23** [comment]
I got opportunity to play with v4 with a flutter web. 

For Authorization Token, I came to know that AuthLink is caching the token internally. 
For some reason, I want to send a new token after some requests like the user logged out and new user logged in.

If there any possible way or workaround to update that new token on AuthLink and subsequent request called will be using the new token?

Reference: https://github.com/zino-app/graphql-flutter/blob/modularization/packages/graphql/lib/src/links/auth_link.dart

**Comment by lazylazyllama** [comment]
> I got opportunity to play with v4 on flutter web.
> 
> For Authorization Token, I came to know that AuthLink is caching the token internally.
> For some reason, I want to send a new token after some requests like the user logged out and new user logged in.
> 
> If there any possible way or workaround to update that new token on AuthLink and subsequent request called will be using the new token?
> 
> Reference: https://github.com/zino-app/graphql-flutter/blob/modularization/packages/graphql/lib/src/links/auth_link.dart

There is an open isssue regarding this: #688

**Comment by lazylazyllama** [comment]
How do I correctly reset the cache in v4?

Right now I am doing this:
```dart
GraphQLProvider.of(context).value.cache.store.reset();
```

But I get a warning saying: `The member 'store' can only be used within instance members of subclasses of 'package:graphql/src/cache/cache.dart'.`

**Comment by micimize** [comment]
@lazylazyllama there isn't a better way right now – we should probably implement apollo's [`client.resetStore`](https://www.apollographql.com/docs/react/caching/advanced-topics/#resetting-the-store) and refetch all live queries.

If you want to work around the warning I think you could do something like
```dart
extension on GraphQLCache {
  void resetStore() => store.reset();
}
```

**Comment by micimize** [comment]
based on https://github.com/zino-app/graphql-flutter/issues/704#issuecomment-676357747 we really need https://github.com/gql-dart/gql/issues/119 solved for backwards compatibility

**Comment by 24601** [comment]
Is there a roadmap/design for Local State Management? I have tried searching issues and don't see much, but would like to see where the thoughts are on this to see how we can consider contributing.

**Comment by micimize** [comment]
@24601 [direct cache access](https://github.com/zino-app/graphql-flutter/blob/modularization/changelog-v3-v4.md#cache-overhaul) can be used for local state management – we don't have any real examples yet but basically you  can `cache.writeQuery` and `writeFragment` to write arbitrary queries to the cache that are then [normalized](https://pub.dev/packages/normalize).

@SanjiKir indicated he was using it in the discord. I think having some docs/examples of usage for it and `typePolicies` (also from `normalize`) would be a pretty beneficial contribution

**Comment by SanjiKir** [comment]
@micimize I wasn't using it as a local state magement. I believe these are 2 different paradigms and we shouldn't mix data layer and app state layer together. What I do is I write to the store on mutation response so I don't have to refetch the query. And sometime I use `readQuery` to get some data for my `app state` to work with.  Basically with `readQuery` and `writeQuery` optimistic mutations became way easier.

**Comment by PhoenixPan** [comment]
> @lazylazyllama there isn't a better way right now – we should probably implement apollo's [`client.resetStore`](https://www.apollographql.com/docs/react/caching/advanced-topics/#resetting-the-store) and refetch all live queries.
> 
> If you want to work around the warning I think you could do something like
> 
> ```dart
> extension on GraphQLCache {
>   void resetStore() => store.reset();
> }
> ```

I am getting the same warning on the store given the extension method...should I put the extension somewhere particular? I am on `graphql_flutter: ^4.0.0-alpha.2`

![image](https://user-images.githubusercontent.com/14355257/93428335-98618480-f902-11ea-99fb-3e16adf2d6c0.png)

**Comment by micimize** [comment]
@PhoenixPan you're right. I've just published `4.0.0-alpha.7` which makes the store public and adds an experimental `client.resetStore` that also refetches queries by default.

**Comment by micimize** [comment]
closed with #648
